#define cfgLog(x, ...)
#define hdd_debugfs_exit(x, ...)
#define hdd_debugfs_init(x, ...) VOS_STATUS_SUCCESS
#define hdd_register_debug_callback(x, ...)
#define hddTraceInit(x, ...)
#define limLog(x, ...)
#define logDbg(x, ...)
#define logDebug(x, ...)
#define logDeinit(x, ...)
#define logInit(x, ...) eSIR_SUCCESS
#define pmmLog(x, ...)
#define schLog(x, ...)
#define smeTraceInit(x, ...)
#define tlTraceInit(x, ...)
#define vos_register_debug_callback(x, ...)
#define vos_register_debugcb_init(x, ...)
#define vos_state_info_dump_all(x, ...)
#define vos_trace_display(x, ...)
#define vosTraceDumpAll(x, ...)
#define vosTraceEnable(x, ...)
#define vos_trace_hex_dump(x, ...)
#define vos_trace_setLevel(x, ...)
#define vos_trace_setValue(x, ...)
#define vos_trace_spin_lock_init(x, ...)
